version: 2

sources:
    - name: jaffle_shop
      description : "data source from dbt tutorial"
      database: dbt-tutorial.
      schema : jaffle_shop
      tables:
        - name : customers
        - name : orders

models:
  - name: fct_customers
    description: This table contains information of customer transaction
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_customers
    tests:
    - dbt_utils.equal_rowcount:
        compare_model: dbt-tutorial.jaffle_shop.customers
    description: This table contains information of customer information
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: This table contains information of order
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
          - dbt_utils.not_null_proportion:
              at_least: 0.95
      - name: customer_id
        tests:
          - not_null
          - dbt_utils.relationships_where:
              to: ref('stg_customers')
              field: customer_id
  - name: compare_relation_columns
    description:  compares the ordinal_position and data_types of columns in two Relations
  - name: compare_queries
    description: similiar with compare_relation_columns but usefull if the relation have difference name
  - name: compare_column_values
    description: compares a column across two queries, and summarizes how many records match perfectly
  - name: compare_all_columns
    description:  test monitors changes data values when code is changed as part of a PR or during development.It sets up a test that will fail if any column values do not match