version: 2

models:
  - name: fct_customers
    description: This table contains information of customer transaction
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_customers
    tests:
    - dbt_utils.equal_rowcount:
        compare_model: dbt-tutorial.jaffle_shop.customers
    description: This table contains information of customer information
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: This table contains information of order
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
          - dbt_utils.not_null_proportion:
              at_least: 0.95
      - name: customer_id
        tests:
          - not_null
          - dbt_utils.relationships_where:
              to: ref('stg_customers')
              field: customer_id
